# Generated by Django 4.0.6 on 2022-11-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='last_punch_date',
        ),
    ]
