# Generated by Django 4.1.1 on 2022-11-03 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_remove_usermodel_last_punch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='last_punch_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Last punch date'),
        ),
    ]
