# Generated by Django 4.1.3 on 2022-12-15 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authapp', '0002_alter_usermodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Group admin')),
                ('group', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group')),
            ],
        ),
    ]
