# Generated by Django 4.1.3 on 2022-12-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_groupadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupadmin',
            name='group_time_zone',
            field=models.IntegerField(default='2', verbose_name='Week'),
        ),
    ]
