# Generated by Django 4.1.1 on 2022-11-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_usermodel_last_punch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_image',
            field=models.ImageField(blank=True, default='staticfiles\\img\\default_user_image.png', upload_to='profile_image/', verbose_name='Profile image'),
        ),
    ]
