# Generated by Django 4.1.1 on 2022-11-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_usermodel_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='last_punch_date',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_punch_week',
            field=models.IntegerField(default='0', verbose_name='Last punch week'),
        ),
    ]
