# Generated by Django 4.1.3 on 2022-12-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_groupadmin_group_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupadmin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
