# Generated by Django 4.1.3 on 2022-12-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_remove_usermodel_last_punch_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_wor_engager',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_wor_leader',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_punch_week',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user_phone_number',
        ),
    ]
