# Generated by Django 4.0.6 on 2022-11-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceManagerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='WOR date')),
                ('is_wor_leader', models.BooleanField(default=False, verbose_name='WOR leader')),
                ('is_wor_engager', models.BooleanField(default=False, verbose_name='WOR engager')),
                ('user_status', models.CharField(choices=[('present', 'PRESENT'), ('not_present', 'NOT_PRESENT'), ('excused', 'EXCUSED'), ('on_vacation', 'ON_VACATION')], default='present', max_length=11)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
