# Generated by Django 4.1.1 on 2022-11-03 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WOR_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wor_date', models.DateField(verbose_name='WOR date')),
            ],
        ),
        migrations.AlterField(
            model_name='attendancemanagermodel',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.wor_date'),
        ),
    ]
