# Generated by Django 4.1.3 on 2022-12-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemanagermodel',
            name='user_status',
            field=models.CharField(choices=[('present', 'PRESENT'), ('absent', 'ABSENT'), ('excused', 'EXCUSED'), ('on_vacation', 'ON_VACATION'), ('comes_later', 'COMES_LATER')], default='present', max_length=11),
        ),
    ]
