# Generated by Django 4.1.1 on 2022-11-03 13:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0003_wor_date_alter_attendancemanagermodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancemanagermodel',
            name='is_wor_engager',
        ),
        migrations.RemoveField(
            model_name='attendancemanagermodel',
            name='is_wor_leader',
        ),
        migrations.AddField(
            model_name='wor_date',
            name='wor_leader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='WOR Learder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wor_date',
            name='wor_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='WOR date'),
        ),
    ]
