# Generated by Django 4.1.1 on 2022-11-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_attendancemanagermodel_is_wor_engager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wor_date',
            name='week_number',
            field=models.IntegerField(default='0', verbose_name='Week'),
        ),
    ]
