# Generated by Django 4.1.1 on 2022-11-08 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_wor_date_week_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wor_date',
            options={'ordering': ['week_number']},
        ),
    ]
