# Generated by Django 4.1.3 on 2022-12-01 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0007_alter_attendancemanagermodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wor_date',
            name='wor_engager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wor_engager', to=settings.AUTH_USER_MODEL, verbose_name='WOR Engager'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wor_date',
            name='wor_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wor_leader', to=settings.AUTH_USER_MODEL, verbose_name='WOR Learder'),
        ),
    ]
