# Generated by Django 4.1.3 on 2022-12-05 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0008_wor_date_wor_engager_alter_wor_date_wor_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wor_date',
            name='wor_engager',
        ),
        migrations.RemoveField(
            model_name='wor_date',
            name='wor_leader',
        ),
        migrations.CreateModel(
            name='WeekAttendanceRoleManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_group', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Role`s group')),
                ('week_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.wor_date')),
                ('wor_engager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wor_engager', to=settings.AUTH_USER_MODEL, verbose_name='WOR Engager')),
                ('wor_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wor_leader', to=settings.AUTH_USER_MODEL, verbose_name='WOR Learder')),
            ],
            options={
                'ordering': ['-week_id'],
            },
        ),
    ]
