# Generated by Django 4.1.3 on 2022-12-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_wor_date_week_end_date_wor_date_week_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wor_date',
            old_name='week_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='wor_date',
            old_name='week_start_date',
            new_name='start_date',
        ),
    ]
