# Generated by Django 4.1.3 on 2022-12-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_rename_week_end_date_wor_date_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wor_date',
            name='wor_date',
        ),
    ]
