# Generated by Django 4.1.3 on 2022-12-06 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_remove_wor_date_wor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wor_date',
            name='wor_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='WOR date'),
        ),
    ]
