# Generated by Django 4.1.3 on 2022-12-06 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_wor_date_wor_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wor_date',
            name='wor_date',
        ),
    ]
